### PR TITLE
Qt6.1 moves moc|uic|rcc from bin to libexec for non windows

### LINKED ISSUE #35: QT6.1+ move binaries
From Qt 6.1+, moc, rcc, and uic binaries moved from QT_HOST_BINS (/usr/bin) to QT_HOST_LIBEXECS (/usr/libexec).
So default path provided by this module is wrong.

From https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.1.0/release-note.txt
> c515ee178f Move build tools to libexec instead of the bin dir
> - Tools that are called by the build system and are unlikely to be
called by the user are now installed to the libexec directory.

### PR DESCRIPTION
**Pull request by Jarod42**
closes #35
Tested with projects from https://github.com/Jarod42/premake-sample-projects/tree/master/projects-qt

### CODE REVIEW

**Comment by dcourtois** [comment]
Hi! Sorry I didn't have time to look at this earlier!
I'm ok with the "idea" behind the change, but I don't like the copy-pasted mess.
I would rename `qtbinpath` to `qttoolpath` everywhere, update the comment in `_preload.lua` to say that it's where the uic/rc/etc. tools are located, and then the only function that would need a real change is `getPaths`: just check the platform/version to return the correct path accordingly.
I can use your PR as a base to do it myself, or you can update this PR, let me know what you prefer.

**Comment by Jarod42** [comment]
I'm ok if you do the changes (you know better than me what you want as changes ;-) )
Do note that `lrelease` (for translation) is still in `bin/`

**Comment by dcourtois** [comment]
Hi again! I've pushed a fix in the `fix_toolpaths` branch. Would you mind checking that this correctly fixes the issue for you?
(and thanks for the `lrelease` note, I'd have missed it otherwise!)

**Comment by dcourtois** [comment]
I've fixed the `fix_toolpaths`,  thanks for the comment! If it's all good, I'll merge it to main.

**Comment by Jarod42** [comment]
Just run the CI, issue spot. about `qtversion`, local test for the proposed fix.

You might probably create a regular PR (easier for review).
I close this one.

**Pull request closed without merging**
